/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  GettingStartedSideBar: [{type: 'autogenerated', dirName: 'Getting Started'}],
  ConceptsSideBar: [{type: 'autogenerated', dirName: 'Concepts'}],
  GuidesSideBar: [{type: 'autogenerated', dirName: 'Guides'}],
  BestPracticesSideBar: [{type: 'autogenerated', dirName: 'Best Practices'}],
  DeveloperConsoleSideBar: [{type: 'autogenerated', dirName: 'Developer Console'}],
  AboutSideBar: [{type: 'autogenerated', dirName: 'About'}],
  

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
